import type { Metadata } from "next";
import {  Delius_Unicase } from "next/font/google";
import "./globals.css";
import AuthProvider from "./Guard/AuthProvider";

const deliusUnicase = Delius_Unicase({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-delius-unicase", // ตั้งชื่อ variable
  display: "swap",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="th"
      className={`${deliusUnicase.variable} `}
    >
      <body>
        <AuthProvider>
          {children}
          <div id="popup-root" />
        </AuthProvider>
      </body>
    </html>
  );
}
